#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# generated by wxGlade 0.9.6 on Wed Jul 15 14:12:04 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class packageFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: packageFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.frame_menubar.Append(wxglade_tmp_menu, "About")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: packageFrame.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: packageFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add((0, 0), 0, 0, 0)
        sizer_1.Add((0, 0), 0, 0, 0)
        sizer_1.Add((0, 0), 0, 0, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def menu_about(self, event):  # wxGlade: packageFrame.<event_handler>
        print("Event handler 'menu_about' not implemented!")
        event.Skip()

# end of class packageFrame

class utauPackage(wx.App):
    def OnInit(self):
        self.frame = packageFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class utauPackage

if __name__ == "__main__":
    app = utauPackage(0)
    app.MainLoop()
